#! /bin/sh

if echo $OSTYPE | grep -i darwin; then
  gunicorn --log-file=- --workers=2 --threads=2 --worker-class=gthread --bind 0.0.0.0:3000 server.core:app
else
  gunicorn --worker-tmp-dir /dev/shm --log-file=- --workers=2 --threads=2 --worker-class=gthread --bind 0.0.0.0:3000 server.core:app
fi
